USE [master]
GO
/****** Object:  Database [cgroup100]    Script Date: 23/01/2023 00:54:24 ******/
CREATE DATABASE [cgroup100]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'cgroup100', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\cgroup100.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'cgroup100_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\cgroup100_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [cgroup100] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cgroup100].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [cgroup100] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cgroup100] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cgroup100] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cgroup100] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cgroup100] SET ARITHABORT OFF 
GO
ALTER DATABASE [cgroup100] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cgroup100] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cgroup100] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cgroup100] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cgroup100] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [cgroup100] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cgroup100] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cgroup100] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cgroup100] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cgroup100] SET  DISABLE_BROKER 
GO
ALTER DATABASE [cgroup100] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cgroup100] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cgroup100] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [cgroup100] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [cgroup100] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cgroup100] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [cgroup100] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [cgroup100] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [cgroup100] SET  MULTI_USER 
GO
ALTER DATABASE [cgroup100] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [cgroup100] SET DB_CHAINING OFF 
GO
ALTER DATABASE [cgroup100] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [cgroup100] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [cgroup100] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [cgroup100] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [cgroup100] SET QUERY_STORE = OFF
GO
USE [cgroup100]
GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 23/01/2023 00:54:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredient](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Image] [nvarchar](1000) NOT NULL,
	[Calories] [int] NOT NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IngredientInRecipes]    Script Date: 23/01/2023 00:54:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IngredientInRecipes](
	[RecipeId] [int] NOT NULL,
	[IngredientId] [int] NOT NULL,
 CONSTRAINT [PK_IngredientInRecipes] PRIMARY KEY CLUSTERED 
(
	[RecipeId] ASC,
	[IngredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 23/01/2023 00:54:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Image] [nvarchar](1000) NOT NULL,
	[CookingMethod] [nvarchar](50) NOT NULL,
	[Time] [int] NOT NULL,
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IngredientInRecipes]  WITH CHECK ADD  CONSTRAINT [FK_IngredientInRecipes_Ingredient] FOREIGN KEY([IngredientId])
REFERENCES [dbo].[Ingredient] ([Id])
GO
ALTER TABLE [dbo].[IngredientInRecipes] CHECK CONSTRAINT [FK_IngredientInRecipes_Ingredient]
GO
ALTER TABLE [dbo].[IngredientInRecipes]  WITH CHECK ADD  CONSTRAINT [FK_IngredientInRecipes_Recipes] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipes] ([Id])
GO
ALTER TABLE [dbo].[IngredientInRecipes] CHECK CONSTRAINT [FK_IngredientInRecipes_Recipes]
GO
USE [master]
GO
ALTER DATABASE [cgroup100] SET  READ_WRITE 
GO
